remote_theme: pages-themes/minimal@v0.2.0
title: Juan Renato Noh
description: Blog y sitio personal sobre tecnología, desarrollo y criterio profesional
markdown: kramdown

plugins:
  - jekyll-paginate

paginate: 6
paginate_path: "/page:num/"
